### ISSUE TITLE
command line interface not available after install

### ISSUE THREAD

**Issue by galapah** [fferrin/pytopojson#2]
I have installed the package into my conda environment with:
`pip install pytopojson`

I try running it:
`python geo2topo.py geojson_file`

Error message:
`python: can't open file 'geo2topo.py': [Errno 2] No such file or directory`

Check which python is called:
`which python`
~/anaconda3/envs/geo/bin/python
`python --version`
Python 3.8.2

Now I check the library path
`ls ~/anaconda3/envs/geo/lib/python3.8/site-packages/pytopojson`

The files geo2topo.py or topoquantize are not present anywhere there.
This is what I have:
bbox.py     cut.py      feature.py   __init__.py  neighbors.py    stitch.py
bisect.py   dedup.py    geometry.py  join.py      prequantize.py  topology.py
bounds.py   delta.py    hash         merge.py     __pycache__     transform.py
commons.py  extract.py  identity.py  mesh.py      quantize.py     untransform.py

My system:
Ubuntu 20.04
pip 20.2.2 (python 3.8)

**Comment by fferrin** [comment]
I'll take a look later today

**Comment by fferrin** [comment]
Thanks for letting me know! I'll take a look later today

**Comment by fferrin** [comment]
@galapah I'm releasing a new version hopefully on January to fix this and some other things. In case you need to use the command line tool, you can always copy that file to your machine and run it from there. I'll let you know as soon as I release the new version

**Comment by fferrin** [comment]
@galapah I just pushed a fix for you problem you mentioned. Let me know if you find any other problem
