### ISSUE TITLE
geo2topo.py -- stuck upon running

### ISSUE THREAD

**Issue by galapah** [fferrin/pytopojson#4]
I have installed the latest version now
```
$ pip uninstall pytopojson
$ pip install pytopojson
```

I try to convert a geojson:
`$ geo2topo.py SOME_FILE.geojson`

Then the system turns seemingly stuck, the cursor (Linux Ubuntu) changes and anywhere (whether in terminal or outside) I click, it produces this line in the terminal:
```
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408
```
After the fourth click and the fourth error line, this output follows
```
~/anaconda3/envs/geo/bin/geo2topo.py: line 6: syntax error near unexpected token `os.path.dirname'
~/anaconda3/envs/geo/bin/geo2topo.py: line 6: `sys.path.append(os.path.dirname(os.path.dirname(__file__)))'
```

and the program terminates.

I have checked the file version:
```
$ which geo2topo.py
~/anaconda3/envs/geo/bin/geo2topo.py
$ sed -n "11p" ~/anaconda3/envs/geo/bin/geo2topo.py
__version__ = "0.0.1"
```

**Comment by fferrin** [comment]
From version `1.1.1` you can run the script by using:
```bash
$ geo2topo <filename>.json
```

Scripts are version `0.0.2` if you want to check it.

Let me know if you find another issue. I'll be glad to help

**Comment by galapah** [comment]
Thank you, after a new reinstall, it works!

**Comment by fferrin** [comment]
Awesome!
