### ISSUE TITLE
Name error 'topology' not defined

### ISSUE THREAD

**Issue by victorkristof** [fferrin/pytopojson#8]
Using the `topo2geo.py` utility raises `NameError: name 'topology' is not defined`. This is because the `topology` variable in https://github.com/fferrin/pytopojson/blob/5128136c9502f4e29330b6cc7e524641bff5f95e/bin/topo2geo.py#L48 should actually be `topology_` (note the underscore).

**Comment by fferrin** [comment]
Thanks for reporting this @victorkristof. Nice catch! You are right, it should be `topology_`. I will fix it later today.

I wonder why it wasn't catch by the tests (https://github.com/fferrin/pytopojson/blob/master/tests/test_topo2geo.py).

**Comment by fferrin** [comment]
@victorkristof this is fixed in the lastest version (1.1.1). You can see the changes [here](https://github.com/fferrin/pytopojson/blob/master/bin/topo2geo.py#L46).

I'll close this for now but feel free to reopen it or create a new one if you have another problem.

**Comment by fferrin** [comment]
@victorkristof I realized that I never updated the version in PyPi. Latest version is `1.1.2` (not `1.1.1`) and you can update yours by executing `pip install pytopojson==1.1.2`.

Sorry for the missunderstanding.

**Comment by victorkristof** [comment]
Ok thanks!
